### ISSUE TITLE
how to just get the ast from process

### ISSUE THREAD

**Issue by zcaudate** [rasendubi/uniorg#1]
I'd like to just get the AST of the org file but currently with

 -   "unified": "9.2.0",
 -  "uniorg-parse": "0.1.3",

```js
const parse          = require('uniorg-parse');
parse("hello")
```
gives this:

```
parse.js:5
    this.Parser = parser_1.parse;
                ^

TypeError: Cannot set property 'Parser' of undefined
    at orgParse (lib/unified-org-parse.js:5:17)
```

and 

```js
const unified        = require('unified');
const parse          = require('uniorg-parse');

const processor = unified()
  .use(parse)

const parser = function (s) {
  processor
    .process(s)
    .then((out) => console.log(out));  
}
parser("hello")
```

gives

```
Index.js:444
    throw new Error('Cannot `' + name + '` without `Compiler`')
    ^

Error: Cannot `process` without `Compiler`
```

**Comment by rasendubi** [comment]
You can use `.parse()` instead of `.process()`.
```
processor
    .parse(s)
    .then((out) => console.log(out));  
```
`process` is a shortcut for parse, run, stringify (https://github.com/unifiedjs/unified#processorprocessfile-done)

Also, if you don't need the rest of unified, you can call `parse` from `uniorg-parse/parser`. (https://github.com/rasendubi/uniorg/tree/master/packages/uniorg-parse#parsestring)

**Comment by zcaudate** [comment]
Awesome. that works great.

btw

the `var { parse } = require('uniorg-parse/parser');` was one of the first things I tried but it also errored:
```
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'uniorg-parse/parser'
```

**Comment by rasendubi** [comment]
hmm... thanks for letting me know. It turns out, parser is exposed under `'uniorg-parse/lib/parser'`.
