### ISSUE TITLE
Horizontal Rules Don't Render

### ISSUE THREAD

**Issue by pokemaster7** [rasendubi/uniorg#11]
[Reference](https://orgmode.org/manual/Horizontal-Rules.html)

> A line consisting of only dashes, and at least 5 of them, is exported as a horizontal line. 

## Example Input

``` org
Hello

-----

World
```

## Output (Org->HTML)

``` html
<div>
<p>Hello</p>
<p>-----</p>
<p>World</p>
</div>
```

## Expected Output

``` html
<div>
<p>Hello</p>
<hr>
<p>World</p>
</div>
```

**Comment by rasendubi** [comment]
Thanks for the report! Fixed in c27e403a2ef5fb9031a098ac5cc6355da5972f57 and published as v0.1.21.
