### ISSUE TITLE
ignoring labels in equations

### ISSUE THREAD

**Issue by roiholtzman** [rasendubi/uniorg#21]
Usually when writing equations in org mode I use a latex environment such as
```
\begin{equation}
\label{eq:1}
\int f(x) dx = 1
\end{equation}
```
The problem is that the label is rendered also.
Can the label be removed?
![Screen Shot 2021-11-19 at 20 05 33](https://user-images.githubusercontent.com/7188052/142670507-3a3bd904-dd7d-4f95-bc53-af5b6455a4a4.png)

**Comment by rasendubi** [comment]
What setup do you use? Do you use org-roam-ui? (this might be relevant then: https://github.com/org-roam/org-roam-ui/issues/131)

It looks like it's using KaTeX and one issue is that `\label` is not supported there yet: https://github.com/KaTeX/KaTeX/issues/2003.

As a workaround, it is possible to add a pass to remove labels from all latex blocks. Something like this should work (not tested):
```js
import visit from 'unist-util-visit';

const processor = unified()
  .use(uniorgParse)
  ...
  .use(() => (tree) => {
    visit(tree, 'latex-environment', (node) => {
      node.value = node.value.replace(/\\label\{.*?\}/g, '');
    });
  })
  ...
```

**Comment by roiholtzman** [comment]
I am using org-roam-ui indeed. So the issue you posted is relevant.

I am not sure how and where should I use the code you posted. (Sorry for my ignorance regarding this).

**Comment by rasendubi** [comment]
Well… it would go into uniorg setup, but that happens to be in org-roam-ui. The code above is way too hacky to be accepted there or in uniorg.

I have one thought though… There seems to be a workaround at https://github.com/KaTeX/KaTeX/issues/2003#issuecomment-843991794 by modifying katex options. @ThomasFKJorna what do you think about exposing katex options to users, so they could apply whatever hacks they want?

**Comment by roiholtzman** [comment]
@rasendubi  I was also wondering if there is a way to include latex macros in the rendering. 
When I was using `org-roam-server` it was using mathjax, and had a header which I could include latex macros.

**Comment by rasendubi** [comment]
Not sure how that looks like, but… KaTeX has a `macros` [option](https://katex.org/docs/options.html). If org-roam-ui allows configuring it, I believe it’ll be possible to add your custom macros there.

**Comment by rasendubi** [comment]
Closing this issue because there is nothing I can do from the uniorg side
