### ISSUE TITLE
[ENH] processing equation references

### ISSUE THREAD

**Issue by roiholtzman** [rasendubi/uniorg#25]
I am using `org-ref` for references. And I am using `org-roam` and `org-roam-ui` to read my notes.
When I reference an equation I write the text `eqref:eq:1`.

This is an example for what I see in the html view:
![](https://user-images.githubusercontent.com/7188052/148577664-3b2fda3d-4805-4df1-b986-733973e5b7e5.png)

Is it possible to add to uniorg the ability to process these references?

(I opened an [issue](https://github.com/org-roam/org-roam-ui/issues/198) initially in the org-roam-ui repository, and I was directed here).

**Comment by rasendubi** [comment]
`uniorg-parse` is configurable so it can parse any link type. I have replied at https://github.com/org-roam/org-roam-ui/issues/198#issuecomment-1010275348 to show how
