### ISSUE TITLE
Update vFile dependency to 5.3.0 version

### ISSUE THREAD

**Issue by Artawower** [rasendubi/uniorg#27]
Right now the version of vFile inside uniorg is compatible with to-vfile 6.1.0, but the latest version of to-vfile is 7.3.0, which is incompatible with vFile 4.2.1, because this version has incompatible types.

<img width="1865" alt="image" src="https://user-images.githubusercontent.com/16963833/153752878-ac57c022-4a1f-4735-ba95-4477f40b3aec.png">

**Comment by rasendubi** [comment]
Yes. See https://github.com/rasendubi/uniorg/issues/24

Is there anything preventing you from downgrading vfile?

**Comment by Artawower** [comment]
Sorry for the inconvenience, I did not find this issue by searching. No, there is no problem with the downgrade, everything is fine and I already did it. Just wanted to notify you 🙂.

**Comment by rasendubi** [comment]
Yeah, no worries. And thanks—it might be a good time to re-visit ESM
support soon

**Comment by ThomasFKJorna** [comment]
If you can use the help, I'd love to help hasten this transition! I've recently been working on a monorepo for some (or quite a few 😅) unified modules in ESM, so I'm somewhat familiar with the challenges this brings (especially with Jest, dear god). Although I'm not certain about the specifics with respect to what this would break specifically, but given that uniorg has been relatively stable for a while I think it would be fine to make a breaking change towards ESM modules.

I would personally also love to be up to date with the rest of the unified ecosystem, as finding the last "safe"/commonjs version of every package every time isn't that great of an experience hahaha.

**Comment by rasendubi** [comment]
@ThomasFKJorna yeah, let’s do this! uniorg is thoroughly tested, so if tests pass, it should be fine. If you want to work on this, you can push a WIP branch and I’ll try to help
