### ISSUE TITLE
failed with yarn dev

### ISSUE THREAD

**Issue by cryoguy** [rasendubi/uniorg#28]
The package worked beautifully before.  But it failed with the following message when I fire "yarn dev" :

`Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /home/tan/proj/uniorg/examples/org-braindump/braindump/node_modules/next/node_modules/postcss/package.json`

**Comment by rasendubi** [comment]
Did you execute `npm install && npm run bootstrap` in the root directory of the project?

Can you show a full reproduction log starting from git clone?

**Comment by cryoguy** [comment]
sorry about the delay.

Here is what I got:

> $ next dev
> warn  - Port 3000 is in use, trying 3001 instead.
> warn  - Port 3001 is in use, trying 3002 instead.
> ready - started server on 0.0.0.0:3002, url: http://localhost:3002
> event - compiled client and server successfully in 336 ms (126 modules)
> wait  - compiling /[[...slug]] (client and server)...
> event - compiled client and server successfully in 191 ms (225 modules)
> failed to process file /2018summary Error: parseList: cannot find item. contentsBegin: 2193, structure: []
>     at Parser.parseList (/home/tan/proj/sandbox/uniorg/braindump/node_modules/uniorg-parse/lib/parser.js:916:19)
>     at Parser.parseElement (/home/tan/proj/sandbox/uniorg/braindump/node_modules/uniorg-parse/lib/parser.js:275:25)
>     at Parser.parseElements (/home/tan/proj/sandbox/uniorg/braindump/node_modules/uniorg-parse/lib/parser.js:79:34)

**Comment by cryoguy** [comment]
I think I got it working. There are a couple of org files failed.  Thanks again!
