### ISSUE TITLE
how to use this to create a braindump?

### ISSUE THREAD

**Issue by cryoguy** [rasendubi/uniorg#3]
Came across your braindump site at org-roam.  Really like to give it a try, but how can I use it?  Say if I have a folder of org files managed via org-roam.   What are the steps to generate a braindump? 

BTW, I can use your example to generate the demo site:

`npx create-next-app --example https://github.com/rasendubi/uniorg/tree/master/examples/org-braindump braindump`  and then `yarn dev`

**Comment by rasendubi** [comment]
Use org-braindump example and copy/link your notes to the `public` directory. All your notes should be available on http://localhost:3000 when running `npm run dev`/`yarn dev`.

The default page is `index.org`. You can change that in [`src/pages/[[...slug]].jsx:46`](https://github.com/rasendubi/uniorg/blob/3323d9fe7ce55ac0cf5ef7e985baed5eed789580/examples/org-braindump/src/pages/%5B%5B...slug%5D%5D.jsx#L46).

You can also check [rasendubi/braindump](https://github.com/rasendubi/braindump/) for a more complex example but that is harder to get running and is tailored to my workflow.

Hope this answers your question

**Comment by cryoguy** [comment]
Thanks for the quick answer. I will give it a try!

**Comment by cryoguy** [comment]
hmm, this is too complicated for me.  I soft-linked all my org files, changed the default page in the `jsx` file, rename your index.org file.  It still displays your default page after `yarn dev` from braindump folder. ?

**Comment by rasendubi** [comment]
Hm... it should have worked.

Could you show the output of `ls ./public` from org-braindump root? Did you restart yarn dev? Could you show your `[[...slug]].jsx` file?

**Comment by rasendubi** [comment]
sorry, misclick

**Comment by cryoguy** [comment]
Very sorry!  I have been wrangling with the wrong public folder. But it still failed to render with my whole org file list.  After playing with a minimumal example, here is what I found.

my list of org files in `./public` folder (my 4 soft-linked org files are marked with a number in braket):

  `
      [1] 20201128204217-embed_images_css_js_etc_in_a_single_html_file.org                     
      changing-posts-directory.org
      code-highlight.org
      [2] GY521-MPU6050-Processing.org
      index.org
      [3] microtype_verbatim_and_elegantpaper_in_org_mode_export.org                                     
      org-roam.org                                                                                               
      styling.org                                                                                                       
      [4] 'Tools and Resources for Spelling and Grammar Check for Emacs.org'
      uniorg.org
`

This is my index org file:
 

> #+TITLE:Testing Uniorg
>    * Posts
>    ** [[microtype_verbatim_and_elegantpaper_in_org_mode_export.org][Microtype, Verbatim and   Elegantpaper in Org-mode export]]
>   ** [[20201128204217-embed_images_css_js_etc_in_a_single_html_file.org][Embed Images, CSS, JS etc  in  a Single HTML File]]
>    ** [[GY521-MPU6050-Processing.org][Arduino with Triple Axis Accelerometer and Gyro Breakout - GY-521 MPU6050]]
>   ** [[Tools and Resources for Spelling and Grammar Check for Emacs.org][Tools and Resources for Spelling and Grammar Check for Emacs]]

After run `yarn dev` and open up [http://localhost:3000/](http://localhost:3000/).

The first and 3rd give give me following error message. The 2nd rendered fine. The fourth one "page not found".

> Server Error
   Error: Error serializing `.title` returned from `getStaticProps` in "/[[...slug]]".
  Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
  This error happened while generating the page. Any console logs will be displayed in the terminal window.
  Call Stack
  isSerializable ...

**Comment by rasendubi** [comment]
It seems like your first and third pages do not have a `#+TITLE:`. Here is a fix: https://github.com/rasendubi/uniorg/commit/2793f39cf6a7aec4678b7b062a6c8a53f0d963b7

For the fourth one, the URL encoding seems to be happening twice. I have disabled one in the orgToHtml: https://github.com/rasendubi/uniorg/commit/9f2e9055e825b286c58f3fbc33374a62fea3968a. That should fix the issue for you, but that is a workaround and not a proper solution as neither uniorg-parse nor uniorg-rehype do the encoding. It's late here, so I will push the proper fix tomorrow.

If you apply the two patches above (or re-create next app), that should fix your issues.

Also, your links are [Internal Links](https://orgmode.org/manual/Internal-Links.html). i.e., they point to the targets in the current document and not other files. To fix that, you should prefix them with either `file:` or `./`:
```org
[[file:Tools and Resources for Spelling and Grammar Check for Emacs.org][Tools and Resources for Spelling and Grammar Check for Emacs]]
```

**Comment by rasendubi** [comment]
Couldn't fall asleep, so here you go…

v0.1.9 now has [improved link parsing and proper url-encoding of file: links](https://github.com/rasendubi/uniorg/commit/e49244f56bf43a410b2b2c985404987726a64729). Though, you will only notice it if you have files with `%` in the name.

I also decided that using file basename as a fallback title is better than empty string: https://github.com/rasendubi/uniorg/commit/eeb10930d9fb92ed2859e60d0da65b65c79fb1a6

I suggest you re-creating the next.js app from template again. This should pull all the changes.

**Comment by cryoguy** [comment]
I own you, man!  Yeah, it is all good now with the MWE.   Very nice!   Any pointer on how to generate an index.org? I could not find much by googling.

**Comment by cryoguy** [comment]
After playing for a couple of hours, I figured out a way of generating index.org.  Here is the issue I met though.  Some of my org files will invoke the following error.   If I softlinked a few files, even left out some of the file listed by index.org.  `yarn dev` generated a site without complaining.  But as soon as I softlinked all the org files, I will have the following error.  Any hint before I narrowing it down one by one tomorrow?

> Server Error
   Error: match error: /\][ \r\t\n]/m against "[fn:perm]: \\tiny As additional permission under GNU GPL version 3            section 7, you may distribute these works without the copy of the GNU GPL normally required by section 4,  provided you include a license notice and a URL through which recipients can access the Corresponding  Source and the copy of the GNU GPL.\\normalsize\n"
    This error happened while generating the page. Any console logs will be displayed in the terminal window.
    Call Stack
    Reader.forceMatch
    ...

**Comment by rasendubi** [comment]
You have found another bug in uniorg :slightly_smiling_face: Uniorg couldn't parse footnote-definition if it wasn't followed by whitespace. Here is a fix: https://github.com/rasendubi/uniorg/commit/67174b11cccaa08d2e79d65a3a12e3020afc02f4

Just run `npm update`/`yarn upgrade`. v0.1.10 has it.

As a warning though, `[fn:perm]: hello` is viewed by org as a footnote-definition with contents `: hello` (not `hello`). `:` is not a part of org-mode syntax.

Also note, that uniorg-rehype currently does not support footnotes (it'll strip them)—ping me if you need this feature.

**Comment by cryoguy** [comment]
Lots of complaints on HTTP urls, also the last one, which I have no clue about.

> TypeError: Invalid URL: http://proxy_ip_or_domain:proxy_port
> 
> TypeError: Invalid URL: http://192.168.1.xx:3000{/php
> 
> TypeError: Cannot read property '1' of null

**Comment by rasendubi** [comment]
I'll try to debug this as is, but could you share the file that's causing that?

**Comment by cryoguy** [comment]
I have over a few hundreds of org files over the years!  Is there a better way to locate the file that is causing the error? I narrow down the files by searching, for other obvious ones. But I do not know what to search for the last one.

**Comment by rasendubi** [comment]
grep for `http://proxy_ip_or_domain:proxy_port` — it most likely comes from your notes

**Comment by rasendubi** [comment]
oh, for the last one... I don't know. I'll add some error handling code to org-braindump to report the name of file

**Comment by rasendubi** [comment]
Pushed a fix for the URL thing and added more logs to find the `property '1' of null` error: https://github.com/rasendubi/uniorg/commit/48338cfc84bf48d37c542b49b059573e133d1b54 (as always, you can apply the patch manually or re-create org-braindump from template)

**Comment by rasendubi** [comment]
For `property '1' of null`: I have reviewed the code and found one place where this could happen. The fix (https://github.com/rasendubi/uniorg/commit/3453e8a6e14aa7136d63ac4fcea1e562ec0a0b28) is available in v0.1.11.

**Comment by cryoguy** [comment]
Thanks!  did fix the last error. Now sth new.

> Server Error
    Error: EISDIR: illegal operation on a directory, read
    This error happened while generating the page. Any console logs will be displayed in the terminal window.

log from terminal:

> ready - started server on http://localhost:3000
> event - compiled successfully
> event - build page: /next/dist/pages/_error
> wait  - compiling...
> event - compiled successfully
> event - build page: /[[...slug]]
> wait  - compiling...
> event - compiled successfully
> incomplete drawer
> incomplete drawer
> incomplete drawer
> [Error: EISDIR: illegal operation on a directory, read] {
>   errno: -21,
>   code: 'EISDIR',
>   syscall: 'read'
> }
> ...

**Comment by rasendubi** [comment]
Pushed [more logging](https://github.com/rasendubi/uniorg/commit/332ae79f3c44b3e7a3c00f4aef989d973eed7eec) to pinpoint the bad file. Re-create from template and try again please.

**Comment by cryoguy** [comment]
Very cool stuff! Thank you so much!  It is a little slow with over 800 org files. Here are some notes and minor things.

> Have to remove agenda file with %% routines, otherwise the following error:
> Error: match (lookingAt) error: /(%%\(.*)[ \t]*$/ against "%%(org-bbdb-anniversaries)\n"

Also have to remove some intermediate _minted*.org files.

> Server Error
> Error: EISDIR: illegal operation on a directory, read
> This error happened while generating the page. Any console logs will be displayed in the terminal window.
> 

The following pop up in the log periodically. 

> event - build page: /next/dist/pages/_error
> wait  - compiling...
> event - compiled successfully
> incomplete drawer
> incomplete drawer
> incomplete drawer

**Comment by rasendubi** [comment]
The issue with diary-sexp (`%%(...)`) happens because the regex is not multiline, so the final `$` does not match newline, but only end of input. You can fix that by making [this regex](https://github.com/rasendubi/uniorg/blob/5314f10b4a598bf65fbdb6d7b098b28b805ea3d3/packages/uniorg-parse/src/parser.ts#L1126) multiline. (Just add an `m` after the closing `/`.) Add a test case to parser.spec.ts with a diary-sexp followed by a newline. (I could do that when I get back to PC.)

What are these _minted files? The issue is strange as it suggest we're trying to read them, but they are not files but directories.

The drawer log happens because uniorg found a :DRAWER: opening, but no :END:. You can `this.r.lime()` add to [the log here](https://github.com/rasendubi/uniorg/blob/5314f10b4a598bf65fbdb6d7b098b28b805ea3d3/packages/uniorg-parse/src/parser.ts#L968). (That will log the opening line so you can grep for it.)

**Comment by rasendubi** [comment]
Fix for diary-sexp parsing: https://github.com/rasendubi/uniorg/commit/26167f3e3c8e8b767e2ca49c17f9a2e47fd60e4c
Fix to exclude directories that match `.org` pattern: https://github.com/rasendubi/uniorg/commit/307d60de4321a6cd874294cbe709436ef9742b76
Adding drawer name to the incomplete drawer message: https://github.com/rasendubi/uniorg/commit/9f1c993bde025e54f2ce812d374824fb4d7b5b32

**Comment by cryoguy** [comment]
you da man!  other than the slowness. It works flawlessly.  Thank you! I will play with it more.

**Comment by rasendubi** [comment]
How slow is it for you? My 800 notes take about 5 seconds to process, but most of that time is spent in other plugins like minification and smartypants.

**Comment by cryoguy** [comment]
maybe I missed sth. After `yarn dev`, it takes up to 8s to open up a link, same to go back to home page. What can I do to deploy it to a local server, and make it more responsive?

**Comment by rasendubi** [comment]
This happens because in development mode it processes all org files on each request (mostly to make sure it finds all backlinks). If you use production version, it processes files only once.

You can use `yarn build` + `yarn start` to run production version. You can also run `next build && next export` to generate a set of static pages.

**Comment by cryoguy** [comment]
Of course, the production version solves the problem!  On the complaints about the drawers, it occurs in two cases:

beamer properties:

> :PROPERTIES:
> :BEAMER_env: block
> :BEAMER_col: 0.5
> :BEAMER_envargs: C[t]
> :END:

and tags:

> * site mirror     :website:

**Comment by rasendubi** [comment]
Could you show more of the files? beamer properties should be parsed as property-drawer, not a regular one. For tags, it shouldn't match drawer at all...

Please also use code blocks (```). Quotes garble the markup.

**Comment by cryoguy** [comment]
```
29-*** Code                                                              :BMCOL:
30:    :PROPERTIES:
31-    :BEAMER_col: 0.7
32-    :END:
33-
34-: Recipes
35-: #+LaTeX_CLASS: beamer
36-: #+BEAMER_FRAME_LEVEL: 2
37-: * Introduction
38-: ** org-mode + beamer =  love
39-: *** Code :BMCOL:
40::     :PROPERTIES:
41-:     :BEAMER_col: 0.7
42-:     :END:
43-: <example block>
44-: *** Simple block  :BMCOL:B_block:
```

```
11:* [[https://rgoswami.me/posts/org-note-workflow/][An Orgmode Note Workflow :: Rohit Goswami — Reflections]] :website:
12-
13-** Article
14-
15-[WARNING] Duplicate identifier 'explanation' at input line 84 column 101
16-**** Background

```

**Comment by cryoguy** [comment]
Another question, to highlight code blocks, I installed `rehype-hightlight` and modified the orgToHtml.js as follows, but without success.  what I am missing or doing wrong?

```
import highlight from 'rehype-highlight';
const processor = unified()
.use(orgParse)
.use(extractExportSettings)
.use(org2rehype)
.use(highlight)
.use(inspectUrls, { inspectEach: processUrl })
.use(toJson);
```

**Comment by rasendubi** [comment]
Have you added the css? rehype-highlight only assigns classes and you need to include one of highlight.js themes (or write your own css)

**Comment by rasendubi** [comment]
Tried both of your examples and they parse perfectly for me. The issue is likely in another file. I'll work on a better reporting, so it shows the file and exact location.

**Comment by cryoguy** [comment]
I did not link the css file!  About the error on drawers, it will help if it logs the files.  It is just too many.  Thanks again!!

**Comment by cryoguy** [comment]
hmm! I add `import '../styles/highlight/github.css';` in `src/page/_app.js`, still the generic highlight. ?

**Comment by rasendubi** [comment]
I have updated the uniorg to report error using unified ecosystem. Now it reports the file and exact location. You'll need to update uniorg and [call the reporter in the api.js](https://github.com/rasendubi/uniorg/commit/829fa1ba96e79fb16d192239992e464eccc36a82#diff-a807ec4df8c23568b969c081c00546043d10b595ef32cda4346eb22f632bcfc2) (or re-create from template)

For code highlight. Did you copy the file github.css file to `/src/styles/highlight/github.css`? If not, you can import it as `import highlight.js/styles/github.css`—this will import it from the node_modules highlight.js package.

If that doesn't work, check that classes are properly attached to the code (use your browser inspector). If they are not, share a piece of code here (with `#+begin_src ... #+end_src`)

**Comment by cryoguy** [comment]
Thanks again for all you help and patience!  You are right and the fault lies in my org files.  On the complaints of `Drawers`, there are only two cases out of all the org files. The `website` tag case happens in one file, and for some reason the tag was push to a new line off the header.  The other case is happend inside a quote of org-capture template but quote block was broken.  Somehow `Uniorg` just relentlessly trying and thus popping up the warnings.   

On code highlight, I did copy the file github.css file to `/src/styles/highlight/github.css`. I will play a little more and report back to you.

**Comment by rasendubi** [comment]
Sure. Anyway, these are warnings, not errors. uniorg doesn't care if you close your drawers or not—it parses it regardless. I just chose to report the warning as this likely shows a user mistake.

**Comment by cryoguy** [comment]
Looks like the `highlight.js` is working now since I am getting the following error. Any thought how to solve it without editing the org files (too many)?

> Server Error
> Error: Unknown language: `emacs-lisp` is not registered
> This error happened while generating the page. Any console logs will be displayed in the terminal window.
>

**Comment by rasendubi** [comment]
Pass in [ignoreMissing](https://github.com/rehypejs/rehype-highlight#optionsignoremissing) option.

**Comment by cryoguy** [comment]
I am using the following:

```
import org2rehype from 'uniorg-rehype';
import highlight from 'rehype-highlight';

const processor = unified()
...
  .use(highlight[options.ignoreMissing=true])
...
```

but got the following errors:

> ReferenceError: options is not defined

**Comment by rasendubi** [comment]
```
  .use(highlight, { ignoreMissing: true })
```

**Comment by cryoguy** [comment]
Took me a couple of hours googling, and failed to find your above snippet. Thanks again!  It seems working now. Tried a few themes, the css showed in html inspector. The highlight is all a little "bleached out".   did a couple of screen capture, but realize I can not attach here.

**Comment by cryoguy** [comment]
looks likes it only using css class from `.hljs` class, not `.hljs-comment` or `.hljs-keyword` etc

```
.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: #474949;
  color: #d1d9e1;
}


.hljs-comment,
.hljs-quote {
  color: #969896;
  font-style: italic;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal,
.hljs-type,
.hljs-addition {
  color: #cc99cc;
}

```

**Comment by rasendubi** [comment]
You should be able to post images here. I'm not sure how to help you as I don't quite understand the issue and cannot reproduce.

**Comment by cryoguy** [comment]
Did not know I can drag the image here.   Here is what I mean.  The `highlight.js` theme (e.g. `rainbow.css` here) is called.
 
![Screenshot_2021-01-24_20-23-38](https://user-images.githubusercontent.com/12690537/105734075-1bb16900-5ee7-11eb-9d74-5ba9f2140b73.png)

And, the content is tagged with other css classes (`.hljs-comment` or `.hljs-keyword` etc. ).

![Screenshot_2021-01-24_20-22-02](https://user-images.githubusercontent.com/12690537/105734118-28ce5800-5ee7-11eb-861a-135a04ae5b6e.png)

But only `.hljs` class was implemented, NOT `.hljs-comment` or `.hljs-keyword` etc.

![Screenshot_2021-01-24_20-22-47](https://user-images.githubusercontent.com/12690537/105734148-2d930c00-5ee7-11eb-8cd8-97d722aa7cbf.png)

**Comment by rasendubi** [comment]
You have to select the span to see which styles apply to it. (It looks like you selected `<code>` on the first screenshot.)

What font/size/weight do you use? It looks like the font is too thin so the browser applies anti-aliasing and partially blends it with the background.

Your options are:
- change `font-family`, so it's more thick by default
- change `font-weight`
- increase `font-size`
- disable `font-smoothing`

**Comment by cryoguy** [comment]
After a careful look, `highlight.js` only tagged `hljs-comment` and `hljs-string` and left the rest inside a pair of parentheses (as shown in the image from my last post). They have no CSS elements associated with them at all.

**Comment by rasendubi** [comment]
Not sure what parentheses are you talking about, but yes, that's how highlight.js works. sh highlighting is not sophisticated.

**Comment by cryoguy** [comment]
sorry, I meant "by a pair quotation marks". Also, when I tried with prism, only elisp code is highlighted.

**Comment by cryoguy** [comment]
what is the right way to pass `alias` options for `prism.js`?  say sh for bash.   I am getting the following error.
> Unknown language: `sh` is not registered Register alias support

**Comment by cryoguy** [comment]
Ok, just FYI.  I could not get `highlight.js` working properly.  I switched to [@neos21/rehype-prism](https://github.com/Neos21/rehype-prism) which allows passing `aliases` option as follows.  Everything is working fine now.   Thanks very much for the great package and all your help!!

```
.use(rehypePrism, {
    aliases: {
      bash: 'sh',
      markdown: 'mdown'
    }
  })
```

**Comment by rasendubi** [comment]
Glad to hear it works!

Is this issue good to close?

**Comment by cryoguy** [comment]
It is all good now!    Thanks!
