### ISSUE TITLE
issue with underscore in title

### ISSUE THREAD

**Issue by cryoguy** [rasendubi/uniorg#30]
Thanks again for this wonderful package!  How do I prevent the underscore to be parsed incorrectly, esp in titles? 
If I have a file with a name like this `workflow_and_productivity_related.org`, the html output will be the following:

![underscore_uniorg](https://user-images.githubusercontent.com/12690537/162388973-4fc32034-1dc5-4f20-9e51-bc4d36bf3392.png)

with html code:

`<a href="[/workflow_and_productivity_related](view-source:http://localhost:3000/workflow_and_productivity_related)">workflow<sub>and</sub><sub>productivity</sub><sub>related.org</sub></a>`

**Comment by cryoguy** [comment]
But it occurs in org file name, not in contents though.

**Comment by rasendubi** [comment]
Can you show the full input document, your code and full output?

**Comment by cryoguy** [comment]
here is the part of the index file in org table format.  I have over thousands org files.

`| [[file:/home/tan/org/what_was_before_the_big_bang_everything_you_need_to_know_bbc_science_focus_magazine.org][what_was_before_the_big_bang_everything_you_need_to_know_bbc_science_focus_magazine.org]]                                                                                                                 |
| [[file:/home/tan/org/what_s_the_difference_between_ntsc_and_pal.org][what_s_the_difference_between_ntsc_and_pal.org]]                                                                                                                                                          |
| [[file:/home/tan/org/what_is_mathematics_the_new_yorker.org][what_is_mathematics_the_new_yorker.org]]                                                                                                                                                                  |
| [[file:/home/tan/org/what_is_life_its_vast_diversity_defies_easy_definition_quanta_magazine.org][what_is_life_its_vast_diversity_defies_easy_definition_quanta_magazine.org]]                                                                                                                              |
| [[file:/home/tan/org/what_can_we_learn_from_the_secret_habits_of_genius_aeon_essays.org][what_can_we_learn_from_the_secret_habits_of_genius_aeon_essays.org]]                                                                                                                                      |
| [[file:/home/tan/org/what_are_the_ingredients_of_pfizer_s_covid_19_vaccine_mit_technology_review.org][what_are_the_ingredients_of_pfizer_s_covid_19_vaccine_mit_technology_review.org]]                                                                                                                         |`
 and the output:

![uni](https://user-images.githubusercontent.com/12690537/162460833-4cc00712-2c4c-4b77-ad63-b4d3c02cf10d.png)

**Comment by rasendubi** [comment]
ok, so this is not title (not `#+title:`) but a normal text/link. The behavior is expected and matches `org-html-export-as-html`. That should be “fixed” if we support `org-use-sub-superscripts`.

**Comment by cryoguy** [comment]
I use [code](https://kitchingroup.cheme.cmu.edu/blog/2014/03/23/Make-a-list-of-org-files-in-all-the-subdirectories-of-the-current-working-directory/) the extract all the org files recursively.   Is there a easy way to extract title using title tag?  so `org-use-sub-superscripts` is not currently supported?

**Comment by rasendubi** [comment]
This should extract the title:
```emacs-lisp
(cdar (org-collect-keywords '("title") '("title")))
```

No, org-use-sub-superscripts is not currently implemented in uniorg.

**Comment by cryoguy** [comment]
this only works with current buffer. 
how to retrieve from a list of org file links?  I have been looking for a way.

`(cdar (org-collect-keywords '("title") '("title")))`

**Comment by rasendubi** [comment]
oh well, you need to pull in file contents to see the title. then you can either parse it as org-mode and use my code above, or extract the title in some other way. If you use org-roam, another option is to query its database instead of walking the filesystem
