### ISSUE TITLE
yarn `create-next-app` command doesn't work

### ISSUE THREAD

**Issue by TomCC7** [rasendubi/uniorg#38]
The correct command should be
```bash
yarn create next-app ...
```

**Comment by rasendubi** [comment]
Thanks for reporting! Would you like to submit a PR? (You can edit the file
right in github ui)

**Comment by TomCC7** [comment]
Sure, the [PR](https://github.com/rasendubi/uniorg/pull/39) is created.

**Comment by rasendubi** [comment]
Thanks for reporting! Would you like to submit a PR? (You can edit the file
right in github ui)
