### ISSUE TITLE
noexport tag is ignored

### ISSUE THREAD

**Issue by cryoguy** [rasendubi/uniorg#4]
A couple of minor things, `noexport` tag is ignored (i.e. the content under is published). Table header (`thead`) is not parsed unless there is a dividing line under (I think the org HTML export got it right). no big deals.  Amazing package! I never thought this is possible. Thank you!

**Comment by cryoguy** [comment]
Never mind, my bad.  I thought org-export forces the first row as thead even without `|-----+-----|` after it.  It does not.

```
  | thead | thead |
  |-------+-------|
  | row1  | row1  |
  | row2  | row2  |
  |-------+-------|
  | row4  | row4  |
  | row5  | row6  |
```

**Comment by rasendubi** [comment]
[Support for `:noexport:`](https://github.com/rasendubi/uniorg/commit/160c0e6bef86c58b5064373c541246ce781e9733) is added in v0.1.17.
