### ISSUE TITLE
Adding class to task headings

### ISSUE THREAD

**Issue by pard68** [rasendubi/uniorg#44]
It'd be great if the task headings ie:

```
* TODO foo
* DONE bar
```

Had a class name added so we can style them separately from the regular headings.

**Comment by rasendubi** [comment]
This can be done as a plugin or by adding a `className` here (conditional on whether headline has a todo keyword): https://github.com/rasendubi/uniorg/blob/da79786f7c3afda29f8fb65052e09ca4fec6d4f3/packages/uniorg-rehype/src/org-to-hast.ts#L261

**Comment by rasendubi** [comment]
Here is an example of how to do that with a plugin: https://github.com/rasendubi/uniorg/pull/46#issuecomment-1236140015
