### ISSUE TITLE
How to solve missing backlinks in page?

### ISSUE THREAD

**Issue by WaytrueDeng** [rasendubi/uniorg#55]
<img width="2980" alt="image" src="https://user-images.githubusercontent.com/61548208/198859112-9931103e-b66a-4181-97ea-18f02bf74c17.png">

**Comment by rasendubi** [comment]
Hey. Could you expand on what's the issue? Can't figure it out from your
screenshot

**Comment by WaytrueDeng** [comment]
> 

Oh, thanks for you so quick reply and incredible work, I use the briandump template and move all my org folder to the public and setting the index to my start page, everything works perfect except that I find there are no backlinks showing, I don't know how to fix it because I don't know the code. So I have to ask for help here.

**Comment by WaytrueDeng** [comment]
I use org-roam v2 with id links

**Comment by rasendubi** [comment]
What format do you use for file names? This fix might be relevant: https://github.com/rasendubi/uniorg/pull/54

**Comment by rasendubi** [comment]
I've just released #54 in [v0.5.5](https://github.com/rasendubi/uniorg/releases/tag/v0.5.5). Could you try upgrading your template?

**Comment by WaytrueDeng** [comment]
> I've just released #54 in [v0.5.5](https://github.com/rasendubi/uniorg/releases/tag/v0.5.5). Could you try upgrading your template?

Yes, it has been fixed!!! thank you!
