### ISSUE TITLE
`katex` not working for parsing Latex and `mathjax` throwing hydration error in NextJS but works fine

### ISSUE THREAD

**Issue by AgrYpn1a** [rasendubi/uniorg#56]
I have tried a few versions of `rehype-katex` and I wasn't able to get it working correctly.
<img width="822" alt="image" src="https://user-images.githubusercontent.com/8715031/209478617-9b64340e-82e9-48db-a23f-8d902a2e58ec.png">

`rehype-mathjax` throws hydration error, but works correctly, I assume this will be fine in the final build but might be worth checking, version that works is `^3.0.0`

**Comment by rasendubi** [comment]
Hey. Do you have a reproducible example? Did you follow katex installation instruction? (most notably, you have to import their css file)

**Comment by AgrYpn1a** [comment]
Yep, you're correct I totally missed that part, after including the stylesheet it works well, thanks!
