### ISSUE TITLE
`#+HTML_ATTR` Attributes for links / images

### ISSUE THREAD

**Issue by AgrYpn1a** [rasendubi/uniorg#61]
I am rather new to `org` but I've found out it's possible to have extra attributes for html elements, in particular, I would need to add attributes to the links, for example `target="_blank"` or `download` but it does not seem to work, or I am doing something wrong.

I tried to do it like its described [here](https://orgmode.org/manual/Links-in-HTML-export.html).

Code I tried: 
```org
#+begin_HOME-CARD
** CV
#+ATTR_HTML: :download
- Download [[/files/mycv.pdf][Rastko Tojagic CV]]
#+end_HOME-CARD

```

**Comment by rasendubi** [comment]
Org does not allow adding attributes without value and they are automatically stripped. Uniorg follows the same rules.

The best way to fix this is to add value for `dowload`:
```org-mode
#+begin_HOME-CARD
** CV
#+ATTR_HTML: :download mycv.pdf
- Download [[/files/mycv.pdf][Rastko Tojagic CV]]
#+end_HOME-CARD
```

Note that this feature is pretty new in uniorg and you need at least uniorg-rehype@0.5.8

**Comment by AgrYpn1a** [comment]
I am using `uniorg-rehype@0.5.5` so I guess that's the core problem. Thanks!
