### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by AgrYpn1a** [rasendubi/uniorg#62]
As from my experience, usually, any org to html export would make a TOC out of headlines and embed it at the start of the page. I was not able to get toc to render, is this feature not supported or am I missing something?

**Comment by rasendubi** [comment]
There is rehype-toc plugin that does the job, so I consider this out of
scope for uniorg (unless somebody wants an org-to-org table of contents).

**Comment by AgrYpn1a** [comment]
Alright, let me look into that and see how it works.

**Comment by AgrYpn1a** [comment]
`rehype-toc` worked well for me, thanks
