### ISSUE TITLE
orgx package might be missing dependencies in package.json

### ISSUE THREAD

**Issue by venikx** [rasendubi/uniorg#78]
Hi! First, I want to say: Lovely project! I've been testing the org-braindump minimal example for a while now, and it's great. 

For my personal site, I wanted to try out Astro instead and I've tried using a minimal example with Astro and `astro-org`. 

However, since `astro-org` requires `rollup-plugin-orgx`, which requires `orgx` I had to install `uniorg-parse` and `uniorg-rehype` before `orgx` was able to function. See errors:
```
12:28:37 AM [vite] Error when evaluating SSR module /.../astro.config.ts: failed to import "astro-org"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'uniorg-parse' imported from /.../node_modules/@uniorgjs/orgx/lib/core.js
```
and
```
12:31:45 AM [vite] Error when evaluating SSR module /.../astro.config.ts: failed to import "astro-org"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'uniorg-rehype' imported from /.../node_modules/@uniorgjs/orgx/lib/core.js
```

I believe  `uniorg-parse` and `uniorg-rehype` are missing from the deps in package.json (or maybe should be peerDeps) of `orgx`? If these at least get defined as peerDependencies we'd get a warning that these are missing when installing `astro-org`.

The scuffed and horrible minimal setup I have, just to try this out, is working now, but I had to install `uniorg-parse` and `uniorg-rehype` even though I'm not currently using it yet.

If orgx is not meant to be used yet, my apologies for reason this issue.

**Comment by rasendubi** [comment]
Hey. yeah, this seems to be a bug. Would you like to submit a PR?

**Comment by venikx** [comment]
> Hey. yeah, this seems to be a bug. Would you like to submit a PR?

Sure, I wanted to get my feet wet on this project, since I can't live without org-mode and the web support kinda pains me atm.

**Comment by rasendubi** [comment]
uhm... I haven't seen this one, although I'm not on nixos

This is most likely because you can't use pre-built binaries on nixos (because of infamous /lib/ld.so). To test this hypothesis, you can try running `./node_modules/.bin/turbo` manually — if that fails with not found error (or ENOENT), that's it.

There seems to be a turbo package in nixpkgs, so we might add it to `nativeBuildInputs`

**Comment by venikx** [comment]
Yeah, noticed the same after reading some of the turbo package. It seems to have similar workarounds as prisma :)
