### ISSUE TITLE
Comments eat keywords

### ISSUE THREAD

**Issue by mkovarik337** [rasendubi/uniorg#8]
In emacs, one can have adjacent keywords and comments. uniorg should support this.

## Input

```
# This is a Comment
#+title: MyTitle
```

## Output

``` json
{
  "type": "org-data",
  "contentsBegin": 0,
  "contentsEnd": 36,
  "children": [
    {
      "type": "section",
      "contentsBegin": 0,
      "contentsEnd": 36,
      "children": [
        {
          "type": "comment",
          "value": "This is a Comment\n+title: MyTitle"
        }
      ]
    }
  ]
}
```

## Expected Output

Parsed file should have two children: one comment node and one keyword node.

**Comment by rasendubi** [comment]
Thanks for the bug report! Fixed in 5cf336b756b16980be9fe56f7fab78798d527756 and published as 0.1.18.
