### ISSUE TITLE
LaTeX: '$$' delimiters don't work across multiple lines

### ISSUE THREAD

**Issue by pokemaster7** [rasendubi/uniorg#9]
`$$` should work across multiple lines. In the [org manual](https://orgmode.org/manual/LaTeX-fragments.html#LaTeX-fragments), it states that:

>Text within the usual LaTeX math delimiters. To avoid conflicts with currency specifications, single ‘$’ characters are only recognized as math delimiters if the enclosed text contains at most two line breaks, is directly attached to the ‘$’ characters with no whitespace in between, and if the closing ‘$’ is followed by whitespace, punctuation or a dash. For the other delimiters, there is no such restriction, so when in doubt, use ‘\(...\)’ as inline math delimiters. 

I feel the code is using the same rules for single `$` as for double `$$`.

## Input
```
$$2+
2$$
```

## Output
``` json
       {
          "type": "paragraph",
          "affiliated": {},
          "contentsBegin": 0,
          "contentsEnd": 8,
          "children": [
            {
              "type": "text",
              "value": "$$2+\n2$$"
            }
          ]
        }
```

## Expected Output
``` json
   {
          "type": "paragraph",
          "affiliated": {},
          "contentsBegin": 0,
          "contentsEnd": 8,
          "children": [
            {
              "type": "latex-fragment",
              "value": "$$2+\n2$$",
              "contents": "2+\n2"
            }
          ]
        }
```

**Comment by rasendubi** [comment]
Thanks for the bug report! Fixed in 3087eee and published as 0.1.18.

Note that the “at most 2 line breaks” requirement seems to be lifted (at least for me with org-mode v9.4.4), so uniorg now supports latex fragments spanning any number of lines as long as they are not broken by org element (paragraph, list, code block, etc.)
