### ISSUE TITLE
In-paragraph line breaks with `\\` is not parsed

### ISSUE THREAD

**Issue by RangHo** [rasendubi/uniorg#99]
To enforce a line break within a paragraph, Org uses `\\` at the end of a line, as shown in [Documentation](https://orgmode.org/manual/Paragraphs.html).

For the following simple Org document...

```org
\\
```

the built-in HTML exporter produces...

```html
<p>
<br>
</p>
```

where currently Uniorg produces...

```html
<p>\\</p>
```

**Comment by rasendubi** [comment]
This now has been implemented in #111 and released at #110.
